### ISSUE TITLE
Could not load your custom find module 'ai'

### ISSUE THREAD

**Issue by aaleksandroff** [cloudgrey-io/appiumpro#9]
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not load your custom find module 'ai'. Did you put it somewhere Appium can 'require' it? Original error: Error: Cannot find module 'test-ai-classifier'`

Capabilities that I'm using:
```
        HashMap<String, String> customFindModules = new HashMap<>();
        customFindModules.put("ai", "test-ai-classifier");
        capabilities.setCapability("customFindModules", customFindModules);
        capabilities.setCapability("shouldUseCompactResponses", false);

        capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.9.2-beta.2");
        driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4725/wd/hub"), 
        capabilities);
```

It fails on clicking the search element:

```
private By search = MobileBy.custom("search");

    @Test
    public void testFindElementUsingAI() {
        driver.findElement(search).click();
    }
```

**Comment by jlipps** [comment]
If you go into the place where appium is installed, and run `node`, you'll get an interactive node.js prompt. From there, run `require("test-ai-classifier");`

If you get an error, it means the classifier module is not correctly installed and accessible to appium.

If not, it means everything is good, just make sure you restarted the appium server after installing it.

**Comment by aaleksandroff** [comment]
Looks like the classifier didn't install correctly with `npm install`. Worked with `npm install -g @latest`. Thanks!

**Comment by BSudheerR** [comment]
I am also facing the similar issue in Mac System with Android Device , with Walmart App 
Error is : 

 Encountered internal error running command: Error: Could not load your custom find module 'ai'. Did you put it somewhere Appium can 'require' it? Original error: Error: Cannot find module 'test-ai-classifier'

Version details :  Node : v10.16.0      npm : 6.9.0 .      Appium Desktop Mac Version : 1.10.0

Source Code : 
HashMap<String, String> customFindModules = new HashMap<>();
customFindModules.put("ai", "test-ai-classifier");
dc.setCapability("appPackage","com.walmart.android");
dc.setCapability("appActivity", "com.walmart.android.app.main.MainActivity");
dc.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.0.1");
dc.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.10.0");
dc.setCapability("customFindModules", customFindModules);
dc.setCapability("shouldUseCompactResponses", false);

Identifiers Used : 
driver.findElement(MobileBy.custom("cart")).click();
driver.findElement(MobileBy.custom("search")).click();

Tried both the suggestions @jlipps and @aaleksandroff , But no luck. 
Note : No errors found while invoking require("test-ai-classifier"); under node console. 

Please help me out , If some one has find similar issues.
Thanks in Advance.

**Comment by mohank2k** [comment]
I am also getting the exact same error while running android driver. But if i see the node -> require("test-ai-classifier") , i am getting the below response.
2019-06-19 17:48:58.486807: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
{ find: [Getter] }
None of the above solutions working.

**Comment by jlipps** [comment]
how did you install test-ai-classifier, and how are you running appium?

**Comment by mohank2k** [comment]
Npm install -g
Tried appium desktop as well as npm install appium.
On the terminal node able to find the module.  But appium doesn't

**Comment by jlipps** [comment]
This will not work with Appium Desktop, only CLI appium. How are you starting Appium? Where is Appium installed on disk?

**Comment by mohank2k** [comment]
Appium is installed in the usr/local/lib/node_modules. The appium is
starting using appium command on the mac terminal.

**Comment by jlipps** [comment]
ok, head into `/usr/local/lib/node_modules/appium` then run `npm install test-ai-classifier`, to make sure it's getting into appium's dependency tree. then restart the appium server and see if it helps.

**Comment by mohank2k** [comment]
I tried the same as well as install -g . No luck. My appium version is 1.13
and I am trying on android driver.

**Comment by jlipps** [comment]
Oh, this won't work on the Android driver, only the UiAutomator2 driver. Will add that to the README if it's not already there.

**Comment by jlipps** [comment]
Noted in https://github.com/testdotai/appium-classifier-plugin/commit/b26b56be66f8bd80abb64039cbebf328ff5832a7

**Comment by mohank2k** [comment]
Oh is it. Let me try uiautomator2 and let you know. Thanks.  If possible
please share sample java code for an android app.

**Comment by mohank2k** [comment]
Hi jlipps,
Thanks for the help. I was able to use the AI classifier on the iOS driver.
But for the android , even though I was using the uiAutomator2 , I am
getting the error.

The capabilities are using the automation name as uiautomator2

when using the remote web driver to start the device,  I am getting could
not load custom find module ai.

When using appium driver to start the device , I am getting  the class
remote web driver of the given context doesn't implement
io.appium.java_client.findByCustom

While same configuration is working for iosdriver.

**Comment by jlipps** [comment]
findByCustom is probably on AppiumDriver, so in Java you'd need to use either IOSDriver or AndroidDriver to access it. or cast to AppiumDriver somehow.

**Comment by RevanthKumarG** [comment]
Hi jlipps,

Thanks in advance for the help. 

I had followed all the necessary steps of installation.
Installed test-ai-classifier in appium root dir
tried with require(test-ai-classifer) in node and seems to be ok.

For the android , even though I was using the uiAutomator2 , I am
getting the error.

 I am getting could not load custom find module ai.

Tried with AppiumDriver and AndroidDriver both.

I am trying out in windows pc.

Please help me set up for andriod.

Thanks
Revanth.

**Comment by anbunathan** [comment]
Dear Jlipps,
I am getting following error.
Pls suggest.

1) Finding an Android element with machine learning magic
       should find the cart button:
     Error: [elementByCustom("ai:cart")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Could not load your custom find module 'ai'. Did you put it somewhere Appium can 'require' it? Original error: Error: Cannot find module 'test-ai-classifier'

Thanks
Anbu

**Comment by ericnana** [comment]
Dear Dr Anbunathan R,

I am facing the same  issue you faced, could you please tell how you properly installed test-ai-classifier.
Actually I installed globally using npm install -g test-ai-classifier and after doing nope and require('test-ai-classifier '). I always get the same error even after restarting the computer. By the way my case is android related. Thanks in advance.

Below the error:
Welcome to Node.js v12.14.0.
Type ".help" for more information.

> require("test-ai-classifier");
Thrown:
Error: Cannot find module 'test-ai-classifier'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
PS: Capabilities: UiAutomator2  set and used Appium version  is 1.19.1

**Comment by anbunathan** [comment]
Dear Eric Nana,
I have explained the steps to solve this issue under the following link:
https://stackoverflow.com/questions/65280383/how-to-properly-install-test-ai-classifier-plugin-for-appium-in-order-to-be-able/65280741#65280741

Regards,
Dr Anbunathan R
